export const 僕が死のうと思ったのは = {
  id: "僕が死のうと思ったのは",
  artist: "中島美嘉",
  name: "僕が死のうと思ったのは",
  lyricist: "秋田ひろむ",
  composer: "秋田ひろむ",
  youtubeId: "AabAbM_Lmuo",
  slug: "boku-ga-shinou-to-omotta-no-wa",
  end: "7:34",
  lyrics: [
    {
      timeStamp: "00:57",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "01:04",
      text: [
        { kanji: "海猫", furigana: "うみねこ" },
        "が",
        { kanji: "桟橋", furigana: "さんばし" },
        "で",
        { kanji: "鳴", furigana: "な" },
        "いたから",
      ],
    },
    {
      timeStamp: "01:10",
      text: [
        { kanji: "波", furigana: "なみ" },
        "の",
        { kanji: "随意", furigana: "ずいい" },
        "に",
        { kanji: "浮", furigana: "う" },
        "かんで",
        { kanji: "消", furigana: "き" },
        "える",
      ],
    },
    {
      timeStamp: "01:16",
      text: [
        { kanji: "過去", furigana: "かこ" },
        "も",
        "ついわんで",
        { kanji: "飛", furigana: "と" },
        "んで",
      ],
    },
    {
      timeStamp: "01:23",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "01:29",
      text: [
        { kanji: "誕生日", furigana: "たんじょうび" },
        "に",
        { kanji: "杏", furigana: "あんず" },
        "の",
        { kanji: "花", furigana: "はな" },
        "が",
        { kanji: "咲", furigana: "さ" },
        "いたから",
      ],
    },
    {
      timeStamp: "01:35",
      text: [
        "その",
        { kanji: "木漏れ日", furigana: "こもれび" },
        "で",
        "うたた",
        { kanji: "寝", furigana: "ね" },
        "したら",
      ],
    },
    {
      timeStamp: "01:41",
      text: [
        { kanji: "虫", furigana: "むし" },
        "の",
        { kanji: "死骸", furigana: "しがい" },
        "と",
        { kanji: "土", furigana: "つち" },
        "になれるかな",
      ],
    },
    {
      timeStamp: "01:48",
      text: [
        { kanji: "薄荷飴", furigana: "はっかあめ" },
        { kanji: "漁港", furigana: "ぎょこう" },
        "の",
        { kanji: "灯台", furigana: "とうだい" },
      ],
    },
    {
      timeStamp: "01:53",
      text: [
        { kanji: "錆", furigana: "さび" },
        "びたアーチ",
        { kanji: "橋", furigana: "はし" },
        { kanji: "捨", furigana: "す" },
        "てた",
        { kanji: "自転車", furigana: "じてんしゃ" },
      ],
    },
    {
      timeStamp: "01:58",
      text: [
        { kanji: "木造", furigana: "もくぞう" },
        "の",
        { kanji: "駅", furigana: "えき" },
        "のストーブの",
        { kanji: "前", furigana: "まえ" },
        "で",
      ],
    },
    {
      timeStamp: "02:02",
      text: [
        "どこにも",
        { kanji: "旅立", furigana: "たびだ" },
        "てない",
        { kanji: "心", furigana: "こころ" },
      ],
    },
    {
      timeStamp: "02:06",
      text: [
        { kanji: "今日", furigana: "きょう" },
        "はまるで",
        { kanji: "昨日", furigana: "きのう" },
        "みたいだ",
      ],
    },
    {
      timeStamp: "02:09",
      text: [
        { kanji: "明日", furigana: "あした" },
        "を",
        { kanji: "変", furigana: "か" },
        "えるなら",
        { kanji: "今日", furigana: "きょう" },
        "を",
        { kanji: "変", furigana: "か" },
        "えなきゃ",
      ],
    },
    {
      timeStamp: "02:12",
      text: ["わかってる わかってるけれど"],
    },
    {
      timeStamp: "02:21",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "02:28",
      text: [
        { kanji: "心", furigana: "こころ" },
        "が",
        { kanji: "空", furigana: "から" },
        "っぽになったから",
      ],
    },
    {
      timeStamp: "02:34",
      text: [
        { kanji: "満", furigana: "み" },
        "たされないと",
        { kanji: "泣", furigana: "な" },
        "いているのは",
      ],
    },
    {
      timeStamp: "02:40",
      text: [
        "きっと",
        { kanji: "満", furigana: "み" },
        "たされたいと",
        { kanji: "願", furigana: "ねが" },
        "うから",
      ],
    },
    {
      timeStamp: "03:12",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "03:19",
      text: [
        { kanji: "靴紐", furigana: "くつひも" },
        "が",
        { kanji: "解", furigana: "と" },
        "けたから",
      ],
    },
    {
      timeStamp: "03:24",
      text: [
        { kanji: "結", furigana: "むす" },
        "び",
        { kanji: "直", furigana: "なお" },
        "すのは",
        { kanji: "苦手", furigana: "にがて" },
        "なんだ",
      ],
    },
    {
      timeStamp: "03:31",
      text: [
        { kanji: "人", furigana: "ひと" },
        "との",
        { kanji: "繋", furigana: "つな" },
        "がり",
        "も",
        "また",
        { kanji: "然", furigana: "しか" },
        "り",
      ],
    },
    {
      timeStamp: "03:37",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "03:43",
      text: [
        { kanji: "少年", furigana: "しょうねん" },
        "が",
        { kanji: "僕", furigana: "ぼく" },
        "を",
        { kanji: "見", furigana: "み" },
        "つめていたから",
      ],
    },
    {
      timeStamp: "03:47",
      text: [
        "ベッドの",
        { kanji: "上", furigana: "うえ" },
        "で",
        { kanji: "土下座", furigana: "どげざ" },
        "してるよ",
      ],
    },
    {
      timeStamp: "03:56",
      text: [
        "あの",
        { kanji: "日", furigana: "ひ" },
        "の",
        { kanji: "僕", furigana: "ぼく" },
        "に",
        "ごめなさいと",
      ],
    },
    {
      timeStamp: "04:02",
      text: ["パソコンの", { kanji: "薄明かり", furigana: "うすあかり" }],
    },
    {
      timeStamp: "04:05",
      text: [
        { kanji: "上階", furigana: "じょうかい" },
        "の",
        { kanji: "部屋", furigana: "へや" },
        "の",
        { kanji: "生活", furigana: "せいかつ" },
        { kanji: "音", furigana: "おと" },
      ],
    },
    {
      timeStamp: "04:08",
      text: ["インターホンのチャイムの", { kanji: "音", furigana: "おと" }],
    },
    {
      timeStamp: "04:11",
      text: [
        { kanji: "耳", furigana: "みみ" },
        "を",
        { kanji: "塞", furigana: "ふさ" },
        "ぐ",
        { kanji: "鳥", furigana: "とり" },
        "かごの",
        { kanji: "少年", furigana: "しょうねん" },
      ],
    },
    {
      timeStamp: "04:14",
      text: [
        { kanji: "見", furigana: "み" },
        "えない",
        { kanji: "敵", furigana: "てき" },
        "と",
        { kanji: "戦", furigana: "たたか" },
        "ってる",
      ],
    },
    {
      timeStamp: "04:17",
      text: [
        { kanji: "六畳", furigana: "ろくじょう" },
        { kanji: "一間", furigana: "ひとま" },
        "のドンキホーテ",
      ],
    },
    {
      timeStamp: "04:20",
      text: ["ゴールはどうせ", { kanji: "醜", furigana: "みにく" }, "いものさ"],
    },
    {
      timeStamp: "04:29",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "04:35",
      text: [
        { kanji: "冷", furigana: "つめ" },
        "たい",
        { kanji: "人", furigana: "ひと" },
        "と",
        { kanji: "言", furigana: "い" },
        "われたから",
      ],
    },
    {
      timeStamp: "04:41",
      text: [
        { kanji: "愛", furigana: "あい" },
        "されたいと",
        { kanji: "泣", furigana: "な" },
        "いているのは",
      ],
    },
    {
      timeStamp: "04:47",
      text: [
        { kanji: "人", furigana: "ひと" },
        "の",
        { kanji: "温", furigana: "ぬく" },
        "もりを",
        { kanji: "知", furigana: "し" },
        "ってしまったから",
      ],
    },
    {
      timeStamp: "05:19",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "05:26",
      text: [
        "あなたが",
        { kanji: "綺麗", furigana: "きれい" },
        "に",
        { kanji: "笑", furigana: "わ" },
        "らう",
        "から",
      ],
    },
    {
      timeStamp: "05:31",
      text: [{ kanji: "死", furigana: "し" }, "ぬことばかり"],
    },
    {
      timeStamp: "05:34",
      text: [{ kanji: "考", furigana: "かんが" }, "えてしまうのは"],
    },
    {
      timeStamp: "05:38",
      text: [
        "きっと",
        { kanji: "生", furigana: "い" },
        "きることに",
        { kanji: "真面目", furigana: "まじめ" },
        "すぎるから",
      ],
    },
    {
      timeStamp: "05:44",
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "が",
        { kanji: "死", furigana: "し" },
        "のうと",
        { kanji: "思", furigana: "おも" },
        "ったのは",
      ],
    },
    {
      timeStamp: "05:50",
      text: [
        "まだ",
        "あなたに",
        { kanji: "出会", furigana: "であ" },
        "ってなかったから",
      ],
    },
    {
      timeStamp: "05:56",
      text: [
        "あなたのような",
        { kanji: "人", furigana: "ひと" },
        "が",
        { kanji: "生", furigana: "う" },
        "まれた",
      ],
    },
    {
      timeStamp: "06:02",
      text: [
        { kanji: "世界", furigana: "せかい" },
        "を",
        { kanji: "少", furigana: "すこ" },
        "し",
        { kanji: "好", furigana: "す" },
        "きになったよ",
      ],
    },
    {
      timeStamp: "06:08",
      text: [
        "あなたのような",
        { kanji: "人", furigana: "ひと" },
        "が",
        { kanji: "生", furigana: "い" },
        "きてる",
      ],
    },
    {
      timeStamp: "06:15",
      text: [
        { kanji: "世界", furigana: "せかい" },
        "に",
        { kanji: "少", furigana: "すこ" },
        "し",
        { kanji: "期待", furigana: "きたい" },
        "するよ",
      ],
    },
  ],
};
