import type { TSong } from "@/songs/Song";

const 打上花火: TSong = {
  id: globalThis.crypto.randomUUID(),
  artist: "DAOKO × 米津玄師",
  name: "打上花火",
  lyricist: "米津玄師",
  composer: "米津玄師",
  youtubeId: "-tKVN2mAKRI",
  slug: "uchiage-hanabi",
  end: "4:52",
  lyrics: [
    {
      timeStamp: "00:23",
      text: [
        "あの",
        { kanji: "日", furigana: "ひ" },
        { kanji: "見渡", furigana: "みわた" },
        "した",
        { kanji: "渚", furigana: "なぎさ" },
        "を　",
        { kanji: "今", furigana: "いま" },
        "も",
        { kanji: "思", furigana: "おも" },
        "い",
        { kanji: "出", furigana: "だ" },
        "すんだ",
      ],
      zh: "那日眺望過的海岸　如今仍能憶起",
    },
    {
      timeStamp: "00:33",
      text: [
        { kanji: "砂", furigana: "すな" },
        "の",
        { kanji: "上", furigana: "うえ" },
        "に",
        { kanji: "刻", furigana: "きざ" },
        "んだ",
        { kanji: "言葉", furigana: "ことば" },
        "　",
        { kanji: "君", furigana: "きみ" },
        "の",
        { kanji: "後ろ姿", furigana: "うしろすがた" },
      ],
      zh: "沙灘上刻劃下的文字　你的背影",
    },
    {
      timeStamp: "00:43",
      text: [
        "寄り",
        { kanji: "返", furigana: "かえ" },
        "す",
        { kanji: "波", furigana: "なみ" },
        "が　",
        { kanji: "足元", furigana: "あしもと" },
        "をよぎり",
        { kanji: "何", furigana: "なに" },
        "かを",
        { kanji: "攫", furigana: "さら" },
        "う",
      ],
      zh: "浪花往返　沖過腳邊帶走了些什麼",
    },
    {
      timeStamp: "00:53",
      text: [
        { kanji: "夕凪", furigana: "ゆうなぎ" },
        "の",
        { kanji: "中", furigana: "なか" },
        "　",
        { kanji: "日暮", furigana: "ひぐ" },
        "れだけが",
        { kanji: "通", furigana: "とお" },
        "り",
        { kanji: "過", furigana: "す" },
        "ぎて",
        { kanji: "行", furigana: "い" },
        "く",
      ],
      zh: "風平浪靜之中　日暮獨自溜走",
    },
    {
      timeStamp: "01:03",
      text: [
        "パッと",
        { kanji: "光", furigana: "ひか" },
        "って",
        { kanji: "咲", furigana: "さ" },
        "いた　",
        { kanji: "花火", furigana: "はなび" },
        "を",
        { kanji: "見", furigana: "み" },
        "ていた",
      ],
      zh: "啪一聲綻放光芒　我們看著煙花",
    },
    {
      timeStamp: "01:08",
      text: [
        "きっとまだ　",
        { kanji: "終", furigana: "お" },
        "わらない",
        { kanji: "夏", furigana: "なつ" },
        "が",
      ],
      zh: "還未結束的夏天　一定會將",
    },
    {
      timeStamp: "01:13",
      text: [
        { kanji: "曖昧", furigana: "あいまい" },
        "な",
        { kanji: "心", furigana: "こころ" },
        "を　",
        { kanji: "解", furigana: "とか" },
        "かして",
        { kanji: "繋", furigana: "つな" },
        "いだ",
      ],
      zh: "曖昧的心　融化後相繫一起",
    },
    {
      timeStamp: "01:18",
      text: [
        "この",
        { kanji: "夜", furigana: "よる" },
        "が　",
        { kanji: "続", furigana: "つづ" },
        "いて",
        { kanji: "欲", furigana: "ほ" },
        "しかった",
      ],
      zh: "多希望　這個夜晚繼續下去",
    },
    {
      timeStamp: "01:33",
      text: [
        "「",
        { kanji: "あと何度", furigana: "あとなんど" },
        { kanji: "君", furigana: "きみ" },
        "と",
        { kanji: "同", furigana: "おな" },
        "じ",
        { kanji: "花火", furigana: "はなび" },
        "を",
        { kanji: "見", furigana: "み" },
        "られるかな」って",
      ],
      zh: "「還能再與你共賞幾次同樣的煙花呢」",
    },
    {
      timeStamp: "01:38",
      text: [
        { kanji: "笑", furigana: "わら" },
        "う",
        { kanji: "顔", furigana: "かお" },
        "に",
        { kanji: "何", furigana: "なに" },
        "ができるだろうか",
      ],
      zh: "為那笑臉我又能做些什麼",
    },
    {
      timeStamp: "01:43",
      text: [
        { kanji: "傷", furigana: "きず" },
        "つくこと　",
        { kanji: "喜", furigana: "よろこ" },
        "ぶこと　",
        { kanji: "繰", furigana: "く" },
        "り",
        { kanji: "返", furigana: "かえ" },
        "す",
        { kanji: "波", furigana: "なみ" },
        "と",
        { kanji: "情動", furigana: "じょうどう" },
      ],
      zh: "受傷 喜悅 浪來浪去與情動",
    },
    {
      timeStamp: "01:48",
      text: [
        { kanji: "焦燥", furigana: "しょうそう" },
        "　",
        { kanji: "最終", furigana: "さいしゅう" },
        { kanji: "列車", furigana: "れっしゃ" },
        "の",
        { kanji: "音", furigana: "おと" },
      ],
      zh: "焦躁 末班列車的聲音",
    },
    {
      timeStamp: "01:53",
      text: [
        { kanji: "何度", furigana: "なんど" },
        "でも　",
        { kanji: "言葉", furigana: "ことば" },
        "にして",
        { kanji: "君", furigana: "きみ" },
        "を",
        { kanji: "呼", furigana: "よ" },
        "ぶよ",
      ],
      zh: "無論幾次 我都會化作話語呼喚你",
    },
    {
      timeStamp: "01:58",
      text: [
        { kanji: "波間", furigana: "なみま" },
        "を",
        { kanji: "選", furigana: "えら" },
        "び　もう",
        { kanji: "一度", furigana: "いちど" },
      ],
      zh: "待浪退時 再一次",
    },
    {
      timeStamp: "02:03",
      text: [
        "もう",
        { kanji: "二度", furigana: "にど" },
        "と",
        { kanji: "悲", furigana: "かな" },
        "しまずに",
        { kanji: "済", furigana: "す" },
        "むように",
      ],
      zh: "是為了讓悲傷不再繼續就此而終",
    },
    {
      timeStamp: "02:20",
      text: [
        "はっと",
        { kanji: "息", furigana: "いき" },
        "を",
        { kanji: "飲", furigana: "の" },
        "めば　",
        { kanji: "消", furigana: "き" },
        "えちゃいそうな",
        { kanji: "光", furigana: "ひかり" },
        "が",
      ],
      zh: "深深倒吸一口氣 那即將消失的光芒",
    },
    {
      timeStamp: "02:26",
      text: ["きっとまだ　", { kanji: "胸", furigana: "むね" }, "に", {
        kanji: "住",
        furigana: "す",
      }, "んでいた"],
      zh: "一定仍會 久留在胸中",
    },
    {
      timeStamp: "02:30",
      text: [
        { kanji: "手", furigana: "て" },
        "を",
        { kanji: "伸", furigana: "の" },
        "ばせば",
        { kanji: "触", furigana: "ふ" },
        "れた　あったかい",
        { kanji: "未来", furigana: "みらい" },
        "は",
      ],
      zh: "只要伸出手便能觸碰 那溫暖的未來",
    },
    {
      timeStamp: "02:36",
      text: ["ひそかに", { kanji: "二人", furigana: "ふたり" }, "を", {
        kanji: "見",
        furigana: "み",
      }, "ていた"],
      zh: "正暗中窺伺著我倆",
    },
    {
      timeStamp: "02:41",
      text: ["パッと", { kanji: "花火", furigana: "はなび" }, "が"],
      zh: "啪一聲煙花",
    },
    {
      timeStamp: "02:44",
      text: [{ kanji: "夜", furigana: "よる" }, "に", {
        kanji: "咲",
        furigana: "さ",
      }, "いた"],
      zh: "於夜裡綻放",
    },
    {
      timeStamp: "02:46",
      text: [{ kanji: "夜", furigana: "よる" }, "に", {
        kanji: "咲",
        furigana: "さ",
      }, "いて"],
      zh: "夜裡綻放後",
    },
    {
      timeStamp: "02:49",
      text: [{ kanji: "静", furigana: "しず" }, "かに", {
        kanji: "消",
        furigana: "き",
      }, "えた"],
      zh: "悄悄消失無蹤",
    },
    {
      timeStamp: "02:51",
      text: [{ kanji: "離", furigana: "はな" }, "さないで"],
      zh: "別讓我走",
    },
    {
      timeStamp: "02:54",
      text: ["もう", { kanji: "少", furigana: "すこ" }, "しだけ"],
      zh: "再一下下就好",
    },
    {
      timeStamp: "02:56",
      text: ["もう", { kanji: "少", furigana: "すこ" }, "しだけ"],
      zh: "再一下下就好",
    },
    {
      timeStamp: "02:58",
      text: ["このままで"],
      zh: "維持現在這樣",
    },
    {
      timeStamp: "03:11",
      text: [
        "あの",
        { kanji: "日", furigana: "ひ" },
        { kanji: "見渡", furigana: "みわた" },
        "した",
        { kanji: "渚", furigana: "なぎさ" },
        "を　",
        { kanji: "今", furigana: "いま" },
        "も",
        { kanji: "思", furigana: "おも" },
        "い",
        { kanji: "出", furigana: "だ" },
        "すんだ",
      ],
      zh: "那日眺望過的海岸　如今仍能憶起",
    },
    {
      timeStamp: "03:20",
      text: [
        { kanji: "砂", furigana: "すな" },
        "の",
        { kanji: "上", furigana: "うえ" },
        "に",
        { kanji: "刻", furigana: "きざ" },
        "んだ",
        { kanji: "言葉", furigana: "ことば" },
        "　",
        { kanji: "君", furigana: "きみ" },
        "の",
        { kanji: "後ろ姿", furigana: "うしろすがた" },
      ],
      zh: "沙灘上刻劃下的文字　你的背影",
    },
    {
      timeStamp: "03:30",
      text: [
        "パッと",
        { kanji: "光", furigana: "ひか" },
        "って",
        { kanji: "咲", furigana: "さ" },
        "いた　",
        { kanji: "花火", furigana: "はなび" },
        "を",
        { kanji: "見", furigana: "み" },
        "ていた",
      ],
      zh: "啪一聲綻放光芒　我們看著煙花",
    },
    {
      timeStamp: "03:35",
      text: [
        "きっとまだ　",
        { kanji: "終", furigana: "お" },
        "わらない",
        { kanji: "夏", furigana: "なつ" },
        "が",
      ],
      zh: "還未結束的夏天　一定會將",
    },
    {
      timeStamp: "03:40",
      text: [
        { kanji: "曖昧", furigana: "あいまい" },
        "な",
        { kanji: "心", furigana: "こころ" },
        "を　",
        { kanji: "解", furigana: "とか" },
        "かして",
        { kanji: "繋", furigana: "つな" },
        "いだ",
      ],
      zh: "曖昧的心　融化後相繫一起",
    },
    {
      timeStamp: "03:45",
      text: [
        "この",
        { kanji: "夜", furigana: "よる" },
        "が　",
        { kanji: "続", furigana: "つづ" },
        "いて",
        { kanji: "欲", furigana: "ほ" },
        "しかった",
      ],
      zh: "多希望　這個夜晚繼續下去",
    },
  ],
};

export default 打上花火;
