import type { TSong } from "@/app/Song";

const 欲望に満ちた青年団: TSong = {
  artist: "ONE OK ROCK",
  name: "欲望に満ちた青年団",
  lyricist: "Taka",
  composer: "Taka",
  youtubeId: "Ds6GfTt_Lv8",
  lyrics: [
    {
      timeStamp: 22.9,
      text: [
        { kanji: "一度", furigana: "いちど" },
        "はあの",
        { kanji: "光", furigana: "ひかり" },
        "を",
        { kanji: "見", furigana: "み" },
        "たんだよ とても",
        { kanji: "綺麗", furigana: "きれい" },
        "で",
      ],
    },
    {
      timeStamp: 28,
      text: [
        "でも",
        { kanji: "今", furigana: "いま" },
        { kanji: "思", furigana: "おも" },
        "えば",
        { kanji: "来", furigana: "き" },
        "てなかった あれは",
        "いわゆる Bad day dreams",
      ],
    },
    {
      timeStamp: 34,
      text: [
        { kanji: "光", furigana: "ひかり" },
        "が",
        { kanji: "眩", furigana: "まぶ" },
        "しすぎて",
        { kanji: "周", furigana: "まわ" },
        "りが",
        { kanji: "見", furigana: "み" },
        "えず ただただ",
        { kanji: "日々", furigana: "ひび" },
        "を",
      ],
    },
    {
      timeStamp: 40,
      text: [
        { kanji: "頬", furigana: "ほほ" },
        "に",
        { kanji: "振", furigana: "ふ" },
        "ってたあの",
        { kanji: "日", furigana: "ひ" },
        " ",
        { kanji: "今", furigana: "いま" },
        "だから",
        { kanji: "笑", furigana: "わら" },
        "えるよ",
      ],
    },
    {
      timeStamp: 56,
      text: [
        { kanji: "一度", furigana: "いちど" },
        "はあの",
        { kanji: "幕", furigana: "まく" },
        "を",
        { kanji: "開", furigana: "あ" },
        "けたんだよ とても",
        { kanji: "重", furigana: "おも" },
        "くて",
      ],
    },
    {
      timeStamp: 61,
      text: [
        "プレッシャー",
        { kanji: "嫌味", furigana: "いやみ" },
        "それに",
        { kanji: "勝", furigana: "か" },
        "つために ただ",
        { kanji: "嫌", furigana: "いや" },
        "な",
        { kanji: "奴", furigana: "やつ" },
        "で",
      ],
    },
    {
      timeStamp: 67,
      text: [
        "そして気が",
        { kanji: "付", furigana: "つ" },
        "くと",
        { kanji: "真", furigana: "ま" },
        "っ",
        { kanji: "暗", furigana: "くら" },
        "な",
        { kanji: "部屋", furigana: "へや" },
        "に",
        { kanji: "一人", furigana: "ひとり" },
        "ぼっちだった",
      ],
    },
    {
      timeStamp: 72,
      text: [
        { kanji: "終", furigana: "お" },
        "わったもう",
        { kanji: "戻", furigana: "もど" },
        "れないなんて",
        { kanji: "歩", furigana: "ある" },
        "くのもやめた",
      ],
    },
    {
      timeStamp: 77,
      text: [
        "でも I'm in it alone, I'm in it alone, waiting, waiting, waiting alone",
      ],
    },
    {
      timeStamp: 83,
      text: [
        { kanji: "お金", furigana: "おかね" },
        "じゃ",
        { kanji: "買", furigana: "か" },
        "えないもの",
        { kanji: "手", furigana: "て" },
        "に",
        { kanji: "入", furigana: "い" },
        "れて",
      ],
    },
    {
      timeStamp: 91,
      text: [
        "もう",
        { kanji: "一度", furigana: "いちど" },
        { kanji: "光", furigana: "ひかり" },
        { kanji: "浴", furigana: "あ" },
        "びて そして",
        { kanji: "今度", furigana: "こんど" },
        "は",
        { kanji: "騙", furigana: "だま" },
        "されるように",
      ],
    },
    {
      timeStamp: 97,
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "らは",
        { kanji: "今", furigana: "いま" },
        { kanji: "目指", furigana: "めざ" },
        "すよ",
        { kanji: "欲望", furigana: "よくぼう" },
        "に",
        { kanji: "満", furigana: "み" },
        "ちた",
        { kanji: "青年団", furigana: "せいねんだん" },
      ],
    },
    {
      timeStamp: 102,
      text: [
        { kanji: "誰", furigana: "だれ" },
        "かが",
        { kanji: "言", furigana: "い" },
        "った",
        { kanji: "言葉", furigana: "ことば" },
        " それすらその",
        { kanji: "時", furigana: "とき" },
        "は",
        { kanji: "流", furigana: "なが" },
        "して",
      ],
    },
    {
      timeStamp: 107,
      text: [
        { kanji: "今", furigana: "いま" },
        "になって",
        { kanji: "気付", furigana: "きづ" },
        "いたよ",
        { kanji: "欲望", furigana: "よくぼう" },
        "に",
        { kanji: "負", furigana: "ま" },
        "けた",
        { kanji: "青年団", furigana: "せいねんだん" },
      ],
    },
    {
      timeStamp: 137,
      text: ["So I know, you know, you know, I know, we have, we have, we have to run"],
    },
    {
      timeStamp: 143,
      text: [
        { kanji: "囚", furigana: "とら" },
        "われないように",
        { kanji: "胴", furigana: "どう" },
        "を",
        { kanji: "上向", furigana: "うわむ" },
        "いて",
        { kanji: "抗", furigana: "あらが" },
        "おう",
      ],
    },
    {
      timeStamp: 154,
      text: [
        "もう",
        { kanji: "一度", furigana: "いちど" },
        { kanji: "光", furigana: "ひかり" },
        "浴びて そして",
        { kanji: "今度", furigana: "こんど" },
        "は",
        { kanji: "騙", furigana: "だま" },
        "されるように",
      ],
    },
    {
      timeStamp: 159,
      text: [
        { kanji: "僕", furigana: "ぼく" },
        "らは",
        { kanji: "今", furigana: "いま" },
        { kanji: "目指", furigana: "めざ" },
        "すよ",
        { kanji: "欲望", furigana: "よくぼう" },
        "に",
        { kanji: "満", furigana: "み" },
        "ちた",
        { kanji: "青年団", furigana: "せいねんだん" },
      ],
    },
    {
      timeStamp: 165,
      text: [
        { kanji: "誰", furigana: "だれ" },
        "かが",
        { kanji: "言", furigana: "い" },
        "った",
        { kanji: "言葉", furigana: "ことば" },
        " それすらその",
        { kanji: "時", furigana: "とき" },
        "は",
        { kanji: "流", furigana: "なが" },
        "して",
      ],
    },
    {
      timeStamp: 170,
      text: [
        { kanji: "今", furigana: "いま" },
        "になって",
        { kanji: "気付", furigana: "きづ" },
        "いたよ",
        { kanji: "欲望", furigana: "よくぼう" },
        "に",
        { kanji: "負", furigana: "ま" },
        "けた",
        { kanji: "青年団", furigana: "せいねんだん" },
      ],
    },
  ],
};

export default 欲望に満ちた青年団;
