type Lyric = {
  timeStamp: number;
  lyric: string;
}

export const lyrics: Lyric[] = [
  { timeStamp: 0, lyric: "好きだね 好きだね 好きだね 好きだね 好きだね" },
  { timeStamp: 11, lyric: "1,2,3,4" },
  { timeStamp: 24, lyric: "最終に間に合ったよ0時ちょい前にそっちに着くよ" },
  { timeStamp: 31, lyric: "ねぇ私もそうってないけど" },
  { timeStamp: 39, lyric: "新大阪駅まで迎えに来てくれたあなたを見たら" },
  { timeStamp: 46, lyric: "待ってるスウェット" },
  { timeStamp: 50, lyric: "今日もうちへ調校か" },
  { timeStamp: 54, lyric: "もう久々みたいな" },
  { timeStamp: 61, lyric: "明日さんたまにはいいじゃん" },
  { timeStamp: 65, lyric: "そうよなって行くの行かれるし" },
  { timeStamp: 77, lyric: "楽しそうにしてたって" },
  { timeStamp: 80, lyric: "あなた以外に連れ戻れんのよ" },
  { timeStamp: 84, lyric: "1,2,3,4" },
  { timeStamp: 96, lyric: "会ってしまうのも良くないよね" },
  { timeStamp: 104, lyric: "毎週は会えないし" },
  { timeStamp: 111, lyric: "通い慣れた道がいつもより長く感じるこの空気" },
  { timeStamp: 119, lyric: "水道筋はこんな日も" },
  { timeStamp: 122, lyric: "いい車線しか動かない" },
  { timeStamp: 126, lyric: "うち着く前に何か飲むもの買ってこようか" },
  { timeStamp: 133, lyric: "気分変えようとしてるんじゃ" },
  { timeStamp: 137, lyric: "そうよなっているのいらないの" },
  { timeStamp: 141, lyric: "一緒に住まへんかとは言わないし" },
  { timeStamp: 149, lyric: "楽しそうにしてたって" },
  { timeStamp: 152, lyric: "そこなり新齢じゃ寂しいよ" },
  { timeStamp: 156, lyric: "近そうでまだ遠い大阪" },
  { timeStamp: 164, lyric: "好きだけどもうしてるって" },
  { timeStamp: 182, lyric: "大阪のおばちゃんと呼ばれたいよ" },
  { timeStamp: 186, lyric: "数えていきたいよ" },
  { timeStamp: 193, lyric: "ねえそんなに笑って" },
  { timeStamp: 204, lyric: "一生に一度の告白やんか" },
  { timeStamp: 208, lyric: "恋しくて憎らしい大阪" },
  { timeStamp: 215, lyric: "楽しそうにしてたって" },
  { timeStamp: 226, lyric: "それはあなたがここに居るか" },
  { timeStamp: 232, lyric: "昔だってあなただけほんまに大切やもん" },
  { timeStamp: 238, lyric: "もうこっちこいやって" },
  { timeStamp: 240, lyric: "遺族してしもたれないの" },
  { timeStamp: 245, lyric: "近そうでまだ遠いか大阪" },
  { timeStamp: 249, lyric: "恋しくて憎らしい大阪" },
];
